name: Lookup - Post Tweet

on:
  schedule:
    # Runs at 9am UTC
    - cron: "0 9 * * *"
  workflow_dispatch:
jobs:
  post_tweet:
    name: Post daily tweet
    runs-on: ubuntu-latest
    steps:
      - uses: chomelc/LookUp@main
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
